$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: mlflow-deployment-2
endpoint_name: mlflow-endpoint
model: azureml:model_20230723_015340@latest
instance_type: Standard_D2as_v4
instance_count: 2
