$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: mlflow-deployment
properties:
  model_name: 'model_20230722_092345'
endpoint_name: mlflow-endpoint
model: azureml:${model_name}@latest
instance_type: Standard_D2as_v4
instance_count: 2
