name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.step.outputs.job_name }}
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: set current directory
      run: cd src
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Experiment Variable
      id: step
      run: |
        # Generate the job name with prefix "job" and current date-time
        job_name="job_$(date +'%Y%m%d_%H%M%S')"
        echo "job_name=${job_name}" >> $GITHUB_OUTPUT
        az ml job create --name $job_name --file src/dev-job.yml --resource-group AzMLChallenge --workspace-name AzMLChallengeDL --stream
  
  register:
    runs-on: ubuntu-latest
    needs: train
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: set current directory
      run: cd src
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Get Experiment Variable
      env:
        OUTPUT: ${{needs.train.outputs.output}}
      run: |
        model_path="azureml://jobs/$OUTPUT/outputs/artifacts/paths/model/"
        model_name="model_$(date +'%Y%m%d_%H%M%S')"
        echo "Model name: $model_name. Model path: $model_path."
        az ml model create --name $model_name --type mlflow_model --path $model_path --resource-group AzMLChallenge --workspace-name AzMLChallengeDL