name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: set current directory
      run: cd src
    - name: run pipeline
      run: az ml job create --name experiment --file src/prod-job.yml --resource-group AzMLChallenge --workspace-name AzMLChallengeDL --stream
  
  register:
    runs-on: ubuntu-latest
    needs: train
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}    
    - name: register model
      run: az ml model register --name model --asset-path azureml://jobs/experiment/outputs/model/model.pkl --resource-group AzMLChallenge --workspace-name AzMLChallengeDL

