name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: set current directory
      run: cd src
    - name: run pipeline
      run: az ml job create --file src/prod-job.yml --resource-group AzMLChallenge --workspace-name AzMLChallengeDL
    - name: Save model to Git
      run: |
        # Configure git with your username and email
        git config --global user.name "Your Name"
        git config --global user.email "your.email@example.com"

        # Add the model artifacts to the git repository
        git add model

        # Commit the changes with a message
        git commit -m "Add trained model artifacts"

        # Push the changes to the remote repository
        git push origin main

