name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: set current directory
      run: cd src
    - name: Set Experiment Variable
      run: |
        # Generate the variable value with prefix "experiment" and current date-time
        name="experiment_$(date +'%Y%m%d_%H%M%S')"
        echo "name=${name}" >> $GITHUB_OUTPUT