name: Pull request trigger

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"