name: My Multi-Stage Pipeline

on:
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: set current directory
        run: cd src
      - name: run pipeline
        run: az ml job create --file src/dev-job.yml --resource-group AzMLChallenge --workspace-name AzMLChallengeDL --stream

  prod:
    runs-on: ubuntu-latest
    needs: dev
    environment:
      name: Prod
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: set current directory
        run: cd src
      - name: run pipeline
        run: az ml job create --file src/prod-job.yml --resource-group AzMLChallenge --workspace-name AzMLChallengeDL --stream
    
  deploy:
    runs-on: ubuntu-latest
    needs: prod
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: set current directory
        run: cd src
      - name: generate endpoint
        run: az ml online-endpoint create --name diabetes-mlflow -f src/endpoint-deploy.yml
      - name: deployment of a MLflow model
        run: az ml online-deployment create --name mlflow-deployment --endpoint diabetes-mlflow -f src/mlflow-deployment.yml --all-traffic
      - name: test endpoint
        run: az ml online-endpoint invoke --name diabetes-mlflow --request-file src/sample-data.json 