trigger:
- main

stages:
- stage: deployDev
  displayName: 'Deploy to development environment'
  jobs:
    - deployment: publishPipeline
      displayName: 'Model Training'
      environment: Dev
      pool:
        vmImage: ubuntu-latest
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo hello world

- stage: deployProd
  dependsOn: deployDev
  condition: succeeded('deployDev')
  displayName: 'Deploy to production environment'
  jobs:
    - deployment: publishPipeline
      displayName: 'Model Training'
      pool:
        vmImage: ubuntu-latest
      environment: Prod
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo how are you
