name: My Multi-Stage Pipeline

on:
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
      - name: Message
        run: |
          echo "Dev"

      # Add other build steps here

  prod:
    runs-on: ubuntu-latest
    needs: dev
    environment:
      name: Prod
    steps:
      - name: Message
        run: |
          echo "Prod"

      # Add deployment steps here
