name: Deployment and testing

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Check az version
        run: az --version  
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: set current directory
        run: cd src
      - name: generate endpoint
        run: az ml online-endpoint create --name diabetes-mlflow -f src/endpoint-deploy.yml --resource-group MLOps --workspace-name MLOpsWS
      