name: Deployment and testing

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install virtualenv
        run: python -m pip install --upgrade pip virtualenv

      - name: Create virtual environment
        run: virtualenv azure_cli_env

      - name: Activate virtual environment
        run: source azure_cli_env/bin/activate

      - name: Install specific versions of Azure CLI and extensions
        run: |
          pip install azure-cli==2.49.0
          pip install azure-cli-core==2.49.0
          pip install azure-cli-telemetry==1.0.8
          pip install msal==1.22.0
          pip install azure-mgmt-resource==21.1.0b1

      - name: Verify installation
        run: az --version
      - name: Install az ml extension
        run: az extension add -n ml -y --version 2.5.0
      - name: Check az version
        run: az --version  
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: set current directory
        run: cd src
      - name: generate endpoint
        run: az ml online-deployment create --name mlflow-deployment-2 --endpoint diabetes-mlflow -f src/mlflow-deployment.yml --resource-group MLOps --workspace-name MLOpsWS --all-traffic
      - name: Deactivate virtual environment
        run: deactivate
      